name: Predator-Cloud
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
jobs:
  run-predator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: pip install aiohttp
      - run: python quantum-system/src/predator.py
